# Write your MySQL query statement below
SELECT CUSTOMER_ID FROM CUSTOMER GROUP BY CUSTOMER_ID
HAVING COUNT(DISTINCT PRODUCT_KEY)=
(SELECT COUNT(PRODUCT_KEY) FROM PRODUCT)
-- (SELECT CUSTOMER_ID FROM CUSTOMER C GROUP BY CUSTOMER_ID HAVING COUNT(DISTINCT C.PRODUCT_KEY)=
-- (SELECT COUNT(PRODUCT_KEY) FROM PRODUCT))