# Write your MySQL query statement below
SELECT E1.NAME FROM EMPLOYEE E1 LEFT JOIN EMPLOYEE E2 ON E1.ID=E2.MANAGERID
GROUP BY E2.MANAGERID HAVING COUNT(E2.ID)>=5
-- SELECT E1.MANAGERID, COUNT(ID) FROM EMPLOYEE E1 GROUP BY E1.MANAGERID