# Write your MySQL query statement below
SELECT S.STUDENT_ID, S.STUDENT_NAME, J.SUBJECT_NAME, COUNT(E.STUDENT_ID) AS
ATTENDED_EXAMS FROM STUDENTS S JOIN SUBJECTS J LEFT JOIN EXAMINATIONS E 
ON S.STUDENT_ID = E.STUDENT_ID AND J.SUBJECT_NAME = E.SUBJECT_NAME 
GROUP BY J.SUBJECT_NAME, S.STUDENT_NAME, S.STUDENT_ID
ORDER BY S.STUDENT_ID, J.SUBJECT_NAME