# Write your MySQL query statement below
SELECT ACTIVITY_DATE AS DAY, COUNT(DISTINCT USER_ID) AS ACTIVE_USERS
FROM ACTIVITY WHERE ACTIVITY_DATE BETWEEN
DATE "2019-06-28" AND DATE "2019-007-27"
GROUP BY ACTIVITY_DATE
