# Write your MySQL query statement below
SELECT SUBSTR(TRANS_DATE,1,7) AS MONTH, COUNTRY, COUNT(ID) AS TRANS_COUNT,
SUM(IF(STATE="approved",1,0)) AS APPROVED_COUNT, SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
SUM(IF(STATE="approved",AMOUNT,0)) AS APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS GROUP BY MONTH, COUNTRY