# Write your MySQL query statement below
SELECT ROUND(SUM(IF(ORDER_DATE=CUSTOMER_PREF_DELIVERY_DATE,1,0))*100/COUNT(ORDER_DATE),2)
AS IMMEDIATE_PERCENTAGE FROM DELIVERY WHERE (CUSTOMER_ID, ORDER_DATE) IN
(SELECT CUSTOMER_ID, MIN(ORDER_DATE) FROM DELIVERY GROUP BY CUSTOMER_ID)