SELECT QUERY_NAME, ROUND(AVG(Q.RATING/Q.POSITION),2) AS QUALITY,
ROUND(SUM(IF(RATING<3,1,0))*100/COUNT(QUERY_NAME),2) AS POOR_QUERY_PERCENTAGE
FROM QUERIES Q WHERE QUERY_NAME IS NOT NULL GROUP BY QUERY_NAME