SELECT 'Low Salary' AS CATEGORY,
COUNT(ACCOUNT_ID) AS ACCOUNTS_COUNT
FROM ACCOUNTS WHERE INCOME<20000
UNION
SELECT 'Average Salary' AS CATEGORY,
COUNT(ACCOUNT_ID) AS ACCOUNTS_COUNT
FROM ACCOUNTS WHERE INCOME>=20000 AND INCOME<=50000
UNION
SELECT 'High Salary' AS CATEGORY,
COUNT(ACCOUNT_ID) AS ACCOUNTS_COUNT
FROM ACCOUNTS WHERE INCOME>50000