# Write your MySQL query statement below
SELECT A1.MACHINE_ID, ROUND(AVG(A1.TIMESTAMP-A2.TIMESTAMP),3) AS PROCESSING_TIME FROM ACTIVITY AS A1 LEFT JOIN 
ACTIVITY AS A2 ON A1.MACHINE_ID=A2.MACHINE_ID WHERE A1.PROCESS_ID=A2.PROCESS_ID AND 
A1.ACTIVITY_TYPE != A2.ACTIVITY_TYPE AND A1.TIMESTAMP>A2.TIMESTAMP GROUP BY A1.MACHINE_ID
