# Write your MySQL query statement below
(SELECT NAME AS RESULTS
FROM MOVIERATING M LEFT JOIN USERS U ON M.USER_ID=U.USER_ID
GROUP BY M.USER_ID
ORDER BY COUNT(*) DESC, U.NAME
LIMIT 1)
UNION ALL
(SELECT TITLE AS RESULTS 
FROM MOVIERATING N LEFT JOIN MOVIES S ON N.MOVIE_ID=S.MOVIE_ID
WHERE CREATED_AT BETWEEN '2020-02-01' AND '2020-02-29'
GROUP BY N.MOVIE_ID
ORDER BY AVG(RATING) DESC, TITLE
LIMIT 1)