# Write your MySQL query statement below
-- SELECT PERSON_NAME FROM QUEUE ORDER BY TURN -- WHERE PERSON_NAME 
-- IN (SELECT PERSON_NAME AS PN
-- FROM QUEUE ORDER BY TURN)
SELECT PERSON_NAME FROM
(SELECT PERSON_NAME, TURN, SUM(WEIGHT) 
OVER (ORDER BY TURN) AS S FROM QUEUE) AS Q1
WHERE S<=1000 ORDER BY TURN DESC LIMIT 1